#if !canImport(ObjectiveC)
import XCTest

extension DebmateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DebmateTests = [
        ("testDictionaryOverwriting", testDictionaryOverwriting),
        ("testLnotices", testLnotices),
        ("testStringExtensions", testStringExtensions),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DebmateTests.__allTests__DebmateTests),
    ]
}
#endif
